### ISSUE TITLE
执行docker-compose pull && docker-compose up时报错

### ISSUE THREAD

**Issue by chenpe32cp** [vesoft-inc/nebula-web-docker#100]
nginx_1     | 2020/06/16 09:11:43 [crit] 1#1: pread() "/etc/nginx/conf.d/nebula.conf" failed (21: Is a directory)
nginx_1     | nginx: [crit] pread() "/etc/nginx/conf.d/nebula.conf" failed (21: Is a directory)
请问这是什么问题？

**Comment by nianiaJR** [comment]
有完整的错误提示么？或者你检查下是不是端口号被占用了：`lsof -i :7001`
另外还有一个可能的原因就是，你之前已经下载过了nginx这个镜像，然后有更改容器内的目录结构，然后启动的时候，结构冲突了，你可以检查下。

**Comment by nianiaJR** [comment]
这个问题我暂时先关了哈，应该就是7001端口被占用，或者docker虚拟机环境没启动起来
