### ISSUE TITLE
图探索时，使用负数id，校验失败

### ISSUE THREAD

**Issue by xuguruogu** [vesoft-inc/nebula-web-docker#103]
![image](https://user-images.githubusercontent.com/6092236/84984173-e5e81d00-b16c-11ea-9ece-e725c973e36e.png)

**Comment by xuguruogu** [comment]
`pattern:/^([a-zA-Z\d]+)*(\n[a-zA-Z\d]+)*(\n)*$/,message:e.get("formRules.nodeIdError")`

`pattern:/^([-+]?[a-zA-Z\d]+)*(\n[-+]?[a-zA-Z\d]+)*(\n)*$/,message:e.get("formRules.nodeIdError")`

哥，fix

**Comment by nianiaJR** [comment]
ok，这个问题我们跟进一下🤝

**Comment by nianiaJR** [comment]
> `pattern:/^([a-zA-Z\d]+)*(\n[a-zA-Z\d]+)*(\n)*$/,message:e.get("formRules.nodeIdError")`
> 
> `pattern:/^([-+]?[a-zA-Z\d]+)*(\n[-+]?[a-zA-Z\d]+)*(\n)*$/,message:e.get("formRules.nodeIdError")`
> 

Hi，这段代码是你从我们的镜像里看见的？

**Comment by xuguruogu** [comment]
> > `pattern:/^([a-zA-Z\d]+)*(\n[a-zA-Z\d]+)*(\n)*$/,message:e.get("formRules.nodeIdError")`
> > `pattern:/^([-+]?[a-zA-Z\d]+)*(\n[-+]?[a-zA-Z\d]+)*(\n)*$/,message:e.get("formRules.nodeIdError")`
> 
> Hi，这段代码是你从我们的镜像里看见的？

打开Chrome调试就看到了

**Comment by nianiaJR** [comment]
哦哦，这个问题我们明天前修复发出去🤝

**Comment by NicolaCage** [comment]
我们已经修复发布了，你跟新一下镜像再试试
