### ISSUE TITLE
显示优化：104 到 214 之间 server 边有两个rank，但是不能显示出来

### ISSUE THREAD

**Issue by whitewum** [vesoft-inc/nebula-web-docker#104]
![image](https://user-images.githubusercontent.com/50101159/85110550-ab05e800-b245-11ea-858c-c61c57c2aba8.png)
```
go from 104 over serve where serve._dst == 215 yield serve._rank


serve._rank
--
20102012
20162017
```

**Comment by whitewum** [comment]
![image](https://user-images.githubusercontent.com/50101159/85111052-5fa00980-b246-11ea-8586-12dd39267180.png)
我得自己写query才明白是两个rank，有点难理解。。。

**Comment by nianiaJR** [comment]
相当于两点之间有同一个关系两条边，只是因为rank不同？是这意思吧，如果在serve后面加（）会不会有助理解？ -> serve(2010012), serve(2016017)

**Comment by whitewum** [comment]
> 相当于两点之间有同一个关系两条边，只是因为rank不同？是这意思吧，如果在serve后面加（）会不会有助理解？ -> serve(2010012), serve(2016017)

nGQl风格是@ 

第二个问题是边上的属性似乎没有办法显示

**Comment by nianiaJR** [comment]
边的属性目前是悬浮显示的
![image](https://user-images.githubusercontent.com/8124783/85240626-6065b500-b46b-11ea-8b55-02312892cfed.png)

**Comment by whitewum** [comment]
> 那就是 serve(@Rank1), server(@rank2）这样？
> 
> 边的属性目前是悬浮显示的
> ![image](https://user-images.githubusercontent.com/8124783/85240626-6065b500-b46b-11ea-8b55-02312892cfed.png)

那优化建议是选到一条边的时候，能有个高亮提示

反正至少我没反应过来。

**Comment by NicolaCage** [comment]
![image](https://user-images.githubusercontent.com/37568394/86308207-26ef2f80-bc4b-11ea-9c6f-8323f35aeb7d.png)

我更改了边id的的生成  和nebula的fetch拼接保持一致。另外我们再增加一个用户自主选择边的 id/类型/属性值 勾选显示，和之前的点那样，这样应该也能满足这个场景？
