### ISSUE TITLE
csv导入数据无法显示边, 通过查询能够查到边的信息

### ISSUE THREAD

**Issue by heshuguo** [vesoft-inc/nebula-web-docker#109]
[data.zip](https://github.com/vesoft-inc/nebula-web-docker/files/4857043/data.zip)
复现材料已附件上传
用的导入命令：
docker run --rm -it --network=host -v /home/consumer/nebula-importer/demo/test:/opt/demo vesoft/nebula-importer --config /opt/demo/example.yaml

**Comment by yixinglu** [comment]
在给 docker 传入指定 workdir 的参数(`-w /opt/demo`)，类似：

```bash
$ docker run --rm -it \
        --network=host \
        -v /home/consumer/nebula-importer/demo/test:/opt/demo \
        -w /opt/demo \
        vesoft/nebula-importer \
        --config /opt/demo/example.yaml
```

查看你的配置文件都是使用的相对路径，所以容器内部最好指定 workdir

**Comment by nianiaJR** [comment]
@heshuguo 你可以把导入的log发出来看看

**Comment by heshuguo** [comment]
(base) [consumer@localhost ~]$ docker run --rm -it --network=host -v /home/consumer/nebula-importer/demo/test:/opt/demo vesoft/nebula-importer --config /opt/demo/example.yaml
2020/07/01 23:59:57 [INFO] clientmgr.go:28: Create 10 Nebula Graph clients
2020/07/01 23:59:57 [INFO] reader.go:64: Start to read file(0): /opt/demo/process.csv, schema: < :VID,process.guid:string,process.time_action:string,process.pid:int,process.path:string,process.cmd:string,process.pname:string >
2020/07/01 23:59:57 [INFO] reader.go:64: Start to read file(1): /opt/demo/parent.csv, schema: < :VID,parent.p_guid:string,parent.time_action:string,parent.p_pid:int,parent.p_path:string,parent.p_cmd:string,parent.p_pname:string >
2020/07/01 23:59:57 [INFO] reader.go:64: Start to read file(2): /opt/demo/follow.csv, schema: < :SRC_VID,:DST_VID,follow.relation:string >
2020/07/02 00:00:05 [INFO] reader.go:180: Total lines of file(/opt/demo/process.csv) is: 29, error lines: 0
2020/07/02 00:00:05 [INFO] reader.go:180: Total lines of file(/opt/demo/follow.csv) is: 29, error lines: 0
2020/07/02 00:00:05 [INFO] statsmgr.go:61: Done(/opt/demo/process.csv): Time(8.04s), Finished(74), Failed(0), Latency AVG(1566us), Batches Req AVG(2069us), Rows AVG(9.20/s)
2020/07/02 00:00:05 [INFO] reader.go:180: Total lines of file(/opt/demo/parent.csv) is: 29, error lines: 0
2020/07/02 00:00:05 [INFO] statsmgr.go:61: Done(/opt/demo/follow.csv): Time(8.05s), Finished(81), Failed(0), Latency AVG(1534us), Batches Req AVG(2028us), Rows AVG(10.07/s)
2020/07/02 00:00:05 [INFO] statsmgr.go:61: Done(/opt/demo/parent.csv): Time(8.05s), Finished(87), Failed(0), Latency AVG(1520us), Batches Req AVG(2016us), Rows AVG(10.81/s)
2020/07/02 00:00:05 [INFO] cmd.go:39: Finish import data, consume time: 8.05s

**Comment by laura-ding** [comment]
可以把操作过程的结果截图发出来吗？

**Comment by heshuguo** [comment]
> @heshuguo 可以把操作过程的结果截图发出来吗？

具体用的数据和配置文件，以及导入命令都提供了。剩下的就是在web端查询，选取follow.csv最后一条，通过ngql能查询到边的信息，但是在图探索那部分没有边的信息。

**Comment by nianiaJR** [comment]
所以说现在所有在终端的查询都是正常的么？只是在web端界面用图探索不正常？

**Comment by nianiaJR** [comment]
问题解决了，是因为导入数据的时候rank非0，但查询的时候没有指定rank，会按默认rank为0进行筛选，所以查不到数据，参考文档：https://docs.nebula-graph.io/manual-EN/2.query-language/4.statement-syntax/2.data-query-and-manipulation-statements/fetch-syntax/#fetch_edge_property
