### ISSUE TITLE
图探索-edge direction 支持bidirect

### ISSUE THREAD

**Issue by jude-zhu** [vesoft-inc/nebula-web-docker#112]
![image](https://user-images.githubusercontent.com/51590253/86306100-f22ca980-bc45-11ea-8dd5-b9e5cdf21994.png)

**Comment by nianiaJR** [comment]
嗯，之前直接用bidirection查询得到的结果不太友好，处理不了。不过利用两次查询倒是可以弥补这个问题，这个需求可以增加。

**Comment by nianiaJR** [comment]
Already support
