### ISSUE TITLE
2020-06-01 10:00:00  数据格式报错

### ISSUE THREAD

**Issue by jingyan6** [vesoft-inc/nebula-web-docker#114]
![image](https://user-images.githubusercontent.com/13622607/86313493-d0d4b900-bc57-11ea-80e5-0e628e5491ff.png)
![image](https://user-images.githubusercontent.com/13622607/86313499-d4684000-bc57-11ea-9905-a5078e9d7bc8.png)

**Comment by nianiaJR** [comment]
你们的日期（column) 在Nebula shchema中定义的是什么类型？
