### ISSUE TITLE
图探索功能建议

### ISSUE THREAD

**Issue by nianiaJR** [vesoft-inc/nebula-web-docker#117]
参照：https://github.com/vesoft-inc/nebula/issues/2210

**Comment by huayaoyue6** [comment]
添加手型工具及缩略图的功能。例如一次性展示多个节点，进行拓展的时候有的节点是游离在屏幕外，即使将图拉到最小也看不到。对页面进行缩小（chrome浏览器的功能）才能看到全览。有的时候看到节点不在屏幕视线内（通过边的关联），可能需要手型工具（或者类似工具）需要将节点拉到视线范围内。

**Comment by huayaoyue6** [comment]
手型工具：展示多个节点的时候有的节点游离在屏幕之外，需要用类似手型工具的东西拖动面板找到节点并进行拓展。
放大缩小或者展示节点有问题：展示多个节点的时候有的节点游离在屏幕之外，缩小到最小还是无法找到，需要用浏览器的缩小功能，但是会引起别的问题：放大后图可能不在屏幕中央，拖拽到视线中央比较麻烦。
