### ISSUE TITLE
图探索添加多个节点没有结果

### ISSUE THREAD

**Issue by xuguruogu** [vesoft-inc/nebula-web-docker#121]
RT

**Comment by nianiaJR** [comment]
是不是对应的space里面，添加的节点并不存在呀？这里的 “添加” 并非是插入节点到 space哦

**Comment by NicolaCage** [comment]
有什么提示吗

**Comment by xuguruogu** [comment]
是数据格式错误导致fetch prop on报错，但是没有提示

**Comment by nianiaJR** [comment]
具体是什么数据格式？或者给个sample数据可以复现一下🤝

**Comment by xuguruogu** [comment]
是sst导入的数据和schema不相符，导致fetch prop on的时候报错：没有这个prop。可能不好复现

**Comment by NicolaCage** [comment]
格式错误在图探索那里应该直接就报错了，理论上应该不能点击添加的🤔

**Comment by NicolaCage** [comment]
再或者如果是添加的起点数据和数据库对不上，应该也有提示不存在

**Comment by xuguruogu** [comment]
> 再或者如果是添加的起点数据和数据库对不上，应该也有提示不存在

现在我们修复了，也不好复现。我估计是fetch的报错没有合理展现。
