### ISSUE TITLE
希望可以添加快捷键 cmd+enter 直接执行输入的语句

### ISSUE THREAD

**Issue by enerai** [vesoft-inc/nebula-web-docker#125]
![image](https://user-images.githubusercontent.com/3956794/86986090-61b21400-c1c5-11ea-86f7-f3d30b798cdb.png)
希望在这个页面可以使用快捷键 cmd+enter 直接执行文本框当中的语句，效果等效于点击右上角的执行按钮

**Comment by xuguruogu** [comment]
支持

**Comment by nianiaJR** [comment]
这个需求已经支持，请更新最新镜像：SHITF + Eneter是运行
