### ISSUE TITLE
点击后 更换图标状态   

### ISSUE THREAD

**Issue by jingyan6** [vesoft-inc/nebula-web-docker#131]
点击完不知道到底点了没
![image](https://user-images.githubusercontent.com/13622607/87108860-d3599300-c295-11ea-8b5b-d4752f538d0c.png)

**Comment by nianiaJR** [comment]
下面不是有运行结果么？是感觉交互上需要增加一个点击效果?

**Comment by jingyan6** [comment]
> 下面不是有运行结果么？是感觉交互上需要增加一个点击效果?

查询比较慢的时候 就是下面是空白 上面也没状态   那到底是执行了没有。。我是需要再点 还是等

**Comment by NicolaCage** [comment]
安排

**Comment by NicolaCage** [comment]
这个功能发布了，最新镜像就可以使用了
