### ISSUE TITLE
Suggest to support keyboard shortcut to submit query

### ISSUE THREAD

**Issue by WLun001** [vesoft-inc/nebula-web-docker#135]
![image](https://user-images.githubusercontent.com/23547929/87843280-ccf69700-c8e5-11ea-9f3d-194d947ac182.png)
 Current behaviour 
- `Enter` -> next line

Expected behaviour 
- `Enter` -> next line
- `CMD + Enter` / `Ctrl + Enter` -> Run query

Need to move the cursor to submit query kind of slow

**Comment by nianiaJR** [comment]
this feature has been added, you can update the image by `docker-compose up`
