### ISSUE TITLE
Data attribute error found in studio

### ISSUE THREAD

**Issue by Shinji-IkariG** [vesoft-inc/nebula-web-docker#137]
The schema is 3 tags, the attributes are string, int, bool
![image](https://user-images.githubusercontent.com/58841610/88269537-cd889680-cd06-11ea-8e80-2dbad4d59e2f.png)

After inserting these 3 attributes for a point, the correct result can be queried in the nebula console. 
![image](https://user-images.githubusercontent.com/58841610/88269572-de390c80-cd06-11ea-92df-442597eb2ae9.png)

But the bool value returns null in studio.
![image](https://user-images.githubusercontent.com/58841610/88269737-2b1ce300-cd07-11ea-9937-3d4fc48fb6e6.png)

<img width="1438" alt="QQ20200723-163357@2x" src="https://user-images.githubusercontent.com/58841610/88269601-e85b0b00-cd06-11ea-9754-9ecfe739493f.png">

**Comment by NicolaCage** [comment]
这个修复发布了
