### ISSUE TITLE
Select Files 页面的体验

### ISSUE THREAD

**Issue by oldLady344** [vesoft-inc/nebula-web-docker#138]
* Prev 和 Next 按钮的位置最好能随着列表加长而自动下移。截图里 Prev 按钮所在的位置，差点以为 Prev 是serve.csv的一个啥操作选项。
* Prev 这个按钮，没有与其他内容长度对齐的要求，最好拼完整单词？
* 这里的Header列是做什么用的？让用户选择是否要带Header列吗？现在不支持带header的csv文件。
* Select Files 建议改为 Upload Files，这里只是上传，并没有选择。按钮里可以简写为 Upload，或者 Select Files？
* Operation ==> Operations
* Name ==> Files 这里并不只是文件名，显示的信息里还包括了文件格式。

![image](https://user-images.githubusercontent.com/61895496/88271490-c7e08000-cd09-11ea-9a70-ea49d81ccd4c.png)

**Comment by nianiaJR** [comment]
Already modified
