### ISSUE TITLE
切换语言

### ISSUE THREAD

**Issue by oldLady344** [vesoft-inc/nebula-web-docker#141]
现在的设计：导入数据时，无论在哪一步切换语言，都会跳回到第一步选择Space，但是，切换语言之前已经完成的工作（例如上传文件）则保持不变。

切换语言的设计，能改成页面保持不变吗，即无论在哪一页切换语言，切换前后的页面不变？

**Comment by nianiaJR** [comment]
这个目前不会这样处理，看起来似乎必要性不大
