### ISSUE TITLE
Error cant run command on nebula web console

### ISSUE THREAD

**Issue by brucemen** [vesoft-inc/nebula-web-docker#149]
Everytime i try run any nebula cmd, it yield this error:

2020/09/29 15:14:12 read tcp 172.28.0.2:34482->192.168.2.105:3699: i/o timeout

2020/09/29 15:14:12.114 [D] [server.go:2802] | 172.28.0.5| 200 |30.026451443s| match| POST /api/db/exec r:/api/db/exec

2020/09/29 15:14:12.451 [D] [server.go:2802] | 172.28.0.5| 200 |27.894018774s| match| POST /api/db/exec r:/api/db/exec

2020/09/29 15:14:12 ErrorCode: E_SESSION_INVALID, ErrorMsg:

**Comment by brucemen** [comment]
It appears on nebula-docer-compose_client_1 container. Could me get any help here. Thanks.

**Comment by brucemen** [comment]
I managed to solve this problem, just stay in nebula-docker-compose v1.

**Comment by nianiaJR** [comment]
You can restart your nebula server and connect it to try again, it seems to be the error about the nebula server.

**Comment by brucemen** [comment]
Ok, thanks you, i will close this issue.

**Comment by mingfang** [comment]
I'm seeing the same problem.
