### ISSUE TITLE
如何修改默认端口7001？

### ISSUE THREAD

**Issue by xjzhou** [vesoft-inc/nebula-web-docker#153]
我把所有7001 改为 9001，

<pre>
[16:32:42][/data/devtools/nebula/nebula-web-docker]-> git diff docker-compose.yml
diff --git a/docker-compose.yml b/docker-compose.yml
index 2e7ea9b..7e6694f 100644
--- a/docker-compose.yml
+++ b/docker-compose.yml
@@ -14,7 +14,7 @@ services:
       USER: root
       UPLOAD_DIR: ${MAPPING_DOCKER_DIR}
     ports:
-      - 7001
+      - 9001
     depends_on:
       - client
     volumes:
@@ -31,7 +31,7 @@ services:
       - ${UPLOAD_DIR}:${MAPPING_DOCKER_DIR}:rw
     command:
       - "--port=5699"
-      - "--callback=http://nginx:7001/api/import/finish"
+      - "--callback=http://nginx:9001/api/import/finish"
   nginx:
     image: nginx:alpine
     volumes:
@@ -44,7 +44,7 @@ services:
     networks:
       - nebula-web
     ports:
-      - 7001:7001
+      - 9001:9001

 networks:
   nebula-web:
</pre>

但启动后仍然看到提示是7001
<pre>
web_1       | 2020-10-16 08:31:34,615 INFO 46 [egg-watcher:application] watcher start success
web_1       | 2020-10-16 08:31:34,616 INFO 46 [egg:core:ready_stat] end ready task /nebula-graph-studio/node_modules/egg-watcher/lib/init.js:15:14, remain []
web_1       | 2020-10-16 08:31:34,706 INFO 28 [master] app_worker#1:46 started at 7001, remain 0 (209100ms)
web_1       | 2020-10-16 08:31:34,706 INFO 28 [master] egg started on http://0.0.0.0:7001 (449256ms)
</pre>

**Comment by xjzhou** [comment]
找到原因了，还要修改 nginx/nginx.conf 里的7001 --> 9001

**Comment by whitewum** [comment]
你还是论坛留言吧。repo issue反而人少
https://discuss.nebula-graph.com.cn/
