### ISSUE TITLE
nginx端口不通

### ISSUE THREAD

**Issue by tmckobe** [vesoft-inc/nebula-web-docker#185]
按步骤操作
1.git clone https://github.com/vesoft-inc/nebula-web-docker.git
2.docker-compose pull
3.docker-compose up -d

端口不通。telnet ***  7001 显示，telnet: connect to address *** : No route to host

请教是什么原因？

**Comment by hetao92** [comment]
看看是不是防火墙的原因呢

**Comment by nianiaJR** [comment]
long time no reponse
