### ISSUE TITLE
显示已经一些易用性的建议

### ISSUE THREAD

**Issue by ConleyKong** [vesoft-inc/nebula-web-docker#191]
1. 画布的拖动问题，节点被拖动后是否可以定位在固定位置而不是自己又弹回去
2. 节点在选中后是否可以删除
3. 双击展开后是否可以双击回退
4. 回退后的子节点无法有效删除，会停留在画布
5. 右键节点后可否增加一些操作菜单，目前的交互鼠标右键是无用的

**Comment by hetao92** [comment]
1. 画布拖动会在后续版本中做出优化
2. 节点选中后可以在画布右上角 '删除选中'按钮执行删除
3. 右上角有回退按钮执行步骤回退
4. 节点删除但渲染有问题目前已经修复，可以更新镜像试试
5. 右键功能我们会做出评估，受限于目前排期问题，会在后续添加支持
感谢提出的建议🤝

**Comment by nianiaJR** [comment]
上面的issue大部分已修复，右键的功能我们已经记录了，后续发布的，这里的topic先关了🤝
