### ISSUE TITLE
子图统计和展示

### ISSUE THREAD

**Issue by nevermore3** [vesoft-inc/nebula-web-docker#195]
1、 可以添加一下子图结果  点和边的数量统计 
2、子图结果导出的csv 文件格式不对
3、是否可以将子图的结果 通过图的形式展示出来

**Comment by hetao92** [comment]
1. 关于功能支持我们会做相应的评估与排期
2. 格式修复会在今天修复并发布上线
3. 目前 console 控制台通过语句查询出子图后在导出 csv 文件按钮旁已经有 '查看子图' 的按钮支持一键导向图探索生成相应图展示
