### ISSUE TITLE
控制台是否可以增加编辑域的调整能力

### ISSUE THREAD

**Issue by ConleyKong** [vesoft-inc/nebula-web-docker#196]
控制台的命令行窗口过小，只能显示三行命令，是否可以支持拖拽调整控制台与结果显示之间的分隔区域或者支持隐藏结果显示区域，让命令的输入能够更方便

**Comment by nianiaJR** [comment]
按cmd是可以扩大的，不只是三行：
![image](https://user-images.githubusercontent.com/8124783/104867186-48133580-597b-11eb-9d73-8a83db9161bc.png)
