### ISSUE TITLE
studio的会话切断机制

### ISSUE THREAD

**Issue by ConleyKong** [vesoft-inc/nebula-web-docker#197]
我正在操作且一直在操作studio，但是会莫名其妙跳转回登录页，登录后先前的操作还全部丢失了，感觉用着不是很舒服

**Comment by nianiaJR** [comment]
这个我们排查一下，谢谢反馈，是一直操作，然后突然断开么？

**Comment by nianiaJR** [comment]
https://github.com/vesoft-inc/nebula-web-docker/issues/133 和这个issue是相似的，先关了
