### ISSUE TITLE
使用nebula graph studio v2.1.4-beta无法显示边

### ISSUE THREAD

**Issue by duduxiao** [vesoft-inc/nebula-web-docker#200]
听说2.0支持cypher，就赶紧用最新版本试试，不过遇到一个问题。从错误来看好像是studio的问题，不过我不确定是否是新的版本中graphd查询返回数据有新的调整导致。 graphd和studio都使用docker-compose 安装
环境：
> nebula graph:v2-nightly  （应该是21号的镜像版本）
> nebula graph studio:v2.1.4-beta (已经确认是docker hub 上最新的版本)

脚本：
> CREATE SPACE test (vid_type = FIXED_STRING(60))
> CREATE TAG user (fullName string NOT NULL , age  int NULL , credit string NULL ) ;
> CREATE EDGE relation (rate double NOT NULL DEFAULT 1.0) ;
> CREATE TAG INDEX user_name on company(fullName(60));

数据：
是csv格式，通过studio导入。
> user.csv:
user001,张三,18,xxxxxxxxx
user002,李四,18,xxxxxxxxx 
> relation.csv:
user001,0.5,user002

match、fetch、go等查询没有问题，图探索页面无法显示边，执行步骤：
1.开始探索->按照VID查询->输入user001->显示张三的点
2.点击”张三“点，选择"拓展",填写 relation，流出，
3.页面无变化，查看调试器，报如下错误

> app.d4122647624b5990f82c.js:1 Uncaught (in promise) TypeError: Cannot read property 'name' of undefined
>     at s (app.d4122647624b5990f82c.js:1)
>     at app.d4122647624b5990f82c.js:1
>     at Array.forEach (<anonymous>)
>     at d (app.d4122647624b5990f82c.js:1)
>     at Object.addNodesAndEdges [as explore/addNodesAndEdges] (app.d4122647624b5990f82c.js:1)
>     at c (vendors.b39ecb65eea80562459c.js:85)
>     at vendors.b39ecb65eea80562459c.js:85
>     at vendors.b39ecb65eea80562459c.js:85
>     at d (vendors.b39ecb65eea80562459c.js:85)
>     at Object.<anonymous> (vendors.b39ecb65eea80562459c.js:85)

**Comment by hetao92** [comment]
fixed
