### ISSUE TITLE
导入nba数据出错

### ISSUE THREAD

**Issue by Lanme** [vesoft-inc/nebula-web-docker#203]
版本：nebula-web-docker v2&nebula-docker-compose v2

import log如下：

2021/02/05 03:44:33 [INFO] connection_pool.go:74: [nebula-clients] connection pool is initialized successfully
2021/02/05 03:44:33 [INFO] clientmgr.go:28: Create 10 Nebula Graph clients
2021/02/05 03:44:33 [INFO] reader.go:64: Start to read file(0): /upload-dir/player.csv, schema: < :VID(string),player.name:string,player.age:int >
2021/02/05 03:44:33 [INFO] reader.go:64: Start to read file(1): /upload-dir/team.csv, schema: < :VID(string),team.name:string >
2021/02/05 03:44:33 [INFO] reader.go:180: Total lines of file(/upload-dir/player.csv) is: 9, error lines: 0
2021/02/05 03:44:33 [INFO] reader.go:64: Start to read file(3): /upload-dir/serve.csv, schema: < :SRC_VID(string),:DST_VID(string),serve.start_year:int,serve.end_year:int >
2021/02/05 03:44:33 [INFO] reader.go:64: Start to read file(2): /upload-dir/follow.csv, schema: < :SRC_VID(string),:DST_VID(string),follow.degree:int >
2021/02/05 03:44:33 [INFO] reader.go:180: Total lines of file(/upload-dir/team.csv) is: 9, error lines: 0
2021/02/05 03:44:33 [INFO] reader.go:180: Total lines of file(/upload-dir/serve.csv) is: 6, error lines: 0
2021/02/05 03:44:33 [INFO] reader.go:180: Total lines of file(/upload-dir/follow.csv) is: 9, error lines: 0
2021/02/05 03:44:33 [INFO] statsmgr.go:61: Done(/upload-dir/player.csv): Time(0.02s), Finished(9), Failed(0), Latency AVG(1070us), Batches Req AVG(1639us), Rows AVG(469.14/s)
2021/02/05 03:44:33 [INFO] statsmgr.go:61: Done(/upload-dir/team.csv): Time(0.02s), Finished(18), Failed(0), Latency AVG(1046us), Batches Req AVG(1599us), Rows AVG(853.65/s)
2021/02/05 03:44:33 [INFO] statsmgr.go:61: Done(/upload-dir/serve.csv): Time(0.02s), Finished(27), Failed(0), Latency AVG(1107us), Batches Req AVG(1748us), Rows AVG(1161.02/s)
2021/02/05 03:44:33 [INFO] statsmgr.go:61: Done(/upload-dir/follow.csv): Time(0.02s), Finished(33), Failed(0), Latency AVG(1089us), Batches Req AVG(1691us), Rows AVG(1342.07/s)

导入信息如下：

配置文件：config.yaml
日志文件：import.log

点相关文件：

该点配置文件：数据源 0

该点错误数据文件：数据源 0Fail.csv

点相关文件：

该点配置文件：数据源 1

该点错误数据文件：数据源 1Fail.csv

边配置文件：

该边配置文件：Edge 0

该边错误数据文件：Edge 0Fail.csv

边配置文件：

该边配置文件：Edge 1

配置文件config.yaml：
{
  "version": "v1rc1",
  "description": "web console import",
  "clientSettings": {
    "concurrency": 10,
    "channelBufferSize": 128,
    "space": "nba",
    "connection": {
      "user": "******",
      "password": "******",
      "address": "******"
    }
  },
  "logPath": "/upload-dir/tmp/import.log",
  "files": [
    {
      "path": "/upload-dir/player.csv",
      "failDataPath": "/upload-dir/tmp/err/数据源 0Fail.csv",
      "batchSize": 10,
      "type": "csv",
      "csv": {
        "withHeader": false,
        "withLabel": false
      },
      "schema": {
        "type": "vertex",
        "vertex": {
          "vid": {
            "index": 0
          },
          "tags": [
            {
              "name": "player",
              "props": [
                {
                  "name": "name",
                  "type": "string",
                  "index": 1
                },
                {
                  "name": "age",
                  "type": "int",
                  "index": 2
                }
              ]
            }
          ]
        }
      }
    },
    {
      "path": "/upload-dir/team.csv",
      "failDataPath": "/upload-dir/tmp/err/数据源 1Fail.csv",
      "batchSize": 10,
      "type": "csv",
      "csv": {
        "withHeader": false,
        "withLabel": false
      },
      "schema": {
        "type": "vertex",
        "vertex": {
          "vid": {
            "index": 0
          },
          "tags": [
            {
              "name": "team",
              "props": [
                {
                  "name": "name",
                  "type": "string",
                  "index": 1
                }
              ]
            }
          ]
        }
      }
    },
    {
      "path": "/upload-dir/follow.csv",
      "failDataPath": "/upload-dir/tmp//err/Edge 0Fail.csv",
      "batchSize": 10,
      "type": "csv",
      "csv": {
        "withHeader": false,
        "withLabel": false
      },
      "schema": {
        "type": "edge",
        "edge": {
          "name": "follow",
          "srcVID": {
            "index": 0
          },
          "dstVID": {
            "index": 1
          },
          "withRanking": false,
          "props": [
            {
              "name": "degree",
              "type": "int",
              "index": 2
            }
          ]
        }
      }
    },
    {
      "path": "/upload-dir/serve.csv",
      "failDataPath": "/upload-dir/tmp//err/Edge 1Fail.csv",
      "batchSize": 10,
      "type": "csv",
      "csv": {
        "withHeader": false,
        "withLabel": false
      },
      "schema": {
        "type": "edge",
        "edge": {
          "name": "serve",
          "srcVID": {
            "index": 0
          },
          "dstVID": {
            "index": 1
          },
          "withRanking": false,
          "props": [
            {
              "name": "start_year",
              "type": "int",
              "index": 2
            },
            {
              "name": "end_year",
              "type": "int",
              "index": 3
            }
          ]
        }
      }
    }
  ]
}
![image](https://user-images.githubusercontent.com/28859589/106997731-586e4180-67be-11eb-9251-268cbdb14684.png)

**Comment by NicolaCage** [comment]
![image](https://user-images.githubusercontent.com/37568394/107005759-244d4d80-67cb-11eb-9c5a-4f113aa3140f.png)

**Comment by NicolaCage** [comment]
看导入log应该完成了的，你说的出错是指？

**Comment by NicolaCage** [comment]
图探索是添加起点vid之后开始继续探索的哦，相关使用手册可以参考这个： https://github.com/vesoft-inc/nebula-web-docker/blob/master/docs/nebula-graph-studio-user-guide-cn.md#%E5%9B%BE%E6%8E%A2%E7%B4%A2
：

**Comment by Lanme** [comment]
好的明白，没看清楚打扰了...

**Comment by whitewum** [comment]
https://discuss.nebula-graph.com.cn/ you're welcome to discuss in the forum
