### ISSUE TITLE
Nebula Graph Studio using Nebula Graph v2.0

### ISSUE THREAD

**Issue by JArma19** [vesoft-inc/nebula-web-docker#207]
I'm facing the following issue:
-I'm running Nebula graph 2.0 and I'm able to connect through nebula-console, and to interact with it.
-nevertheless when I try to connect to it by using Nebula Graph Studio, I'm able to login, but not to interact.
 For instance, typing the same queries I inserted in the console at the previous point in the nebula graph studio console I always get a  `i/o timeout` error. I can't figure out which problem could it be. Thanks

**Comment by nianiaJR** [comment]
Which's the version of your Nebula Graph Studio? I guess that you need `cd v2/` like this folder: https://github.com/vesoft-inc/nebula-web-docker/tree/master/v2 and command `docker-compose up`.

**Comment by JArma19** [comment]
it worked, thanks for your support
