### ISSUE TITLE
web界面与数据连接失败

### ISSUE THREAD

**Issue by chenpe32cp** [vesoft-inc/nebula-web-docker#209]
![_storage_emulated_0_DCIM_iWind_windexport_1614939271747](https://user-images.githubusercontent.com/27393416/110101862-0c271900-7ddf-11eb-9870-894e6ba28229.jpg)
我的nebula graph与 stuio都是2.0版本，请问这是什么问题呢

**Comment by nianiaJR** [comment]
这个问题在这里继续跟踪哈：https://discuss.nebula-graph.com.cn/t/topic/3033
