### ISSUE TITLE
使用后的一些建议

### ISSUE THREAD

**Issue by codlin** [vesoft-inc/nebula-web-docker#210]
1. 在`配置数据库`页面，`密码`的Input属性是否可以改成password，既可以避免明文输入，浏览器还可以自动同步
2. `控制台`有`查看历史`按钮，希望也可以增加`清除历史`功能

**Comment by nianiaJR** [comment]
> 1. 在`配置数据库`页面，`密码`的Input属性是否可以改成password，既可以避免明文输入，浏览器还可以自动同步
> 2. `控制台`有`查看历史`按钮，希望也可以增加`清除历史`功能
好的，密码这个以前是加了password的，这个bug尽快修复。
另外，清除历史的需求初衷是不希望其他人看到查询记录么？

**Comment by codlin** [comment]
有这方面的考虑，譬如说我通过命令修改了密码，而那个密码的命令就一直在那里，这些信息存在log里感觉不妥。

**Comment by nianiaJR** [comment]
> 有这方面的考虑，譬如说我通过命令修改了密码，而那个密码的命令就一直在那里，这些信息存在log里感觉不妥。

好的，这个可以考虑加一下

**Comment by nianiaJR** [comment]
这两个问题已经修改发布了：https://github.com/vesoft-inc/nebula-web-docker/commit/c378153bbda6e7cd648129484c2c8c8dff1885e8
