### ISSUE TITLE
new-line character '\' returns an error

### ISSUE THREAD

**Issue by jude-zhu** [vesoft-inc/nebula-web-docker#22]
```
YIELD 11 +             \  
/* Multiple-line comment       \
Use backslash as line break.   \
*/ 12
```

![1](https://user-images.githubusercontent.com/51590253/72695281-eefba080-3b72-11ea-905c-e490b2477fc1.png)

**Comment by nianiaJR** [comment]
why you use + operator? It's not a nGQL.

**Comment by jude-zhu** [comment]
'\' in nGQL is for new line.

**Comment by nianiaJR** [comment]
> "\" in nGQL is a line break.

You don't need to '\n' , just press enter to break line in our editor.
