### ISSUE TITLE
Why Nebula graph studio needs docker

### ISSUE THREAD

**Issue by ansarizafar** [vesoft-inc/nebula-web-docker#25]
Why not just provide a binary for running Nebula graph? Why docker is required?

**Comment by nianiaJR** [comment]
It's our fist beta version of Nebula Studio, which to touch some users giving some feedback. We are planning to move it online as a SaaS, it's comming soon.

**Comment by ansarizafar** [comment]
Nebula graph Studio will not be a free and opensource product right?

**Comment by nianiaJR** [comment]
> Nebula graph Studio will not be a free and opensource product right?

No, the Nebula graph Studio itselft is free. you can deploy it yourself. But we will include it as our part service of saas, the saas will be charged according to your need.

**Comment by ansarizafar** [comment]
Ok Got it Thanks.
