### ISSUE TITLE
No data in use

### ISSUE THREAD

**Issue by Amber1990Zhang** [vesoft-inc/nebula-web-docker#32]
![image](https://user-images.githubusercontent.com/42762957/76819499-50727f80-6843-11ea-8884-a4c591517e3e.png)
 `SHOW SPACE` shows there are 3 spaces but none is listed in the use column.

**Comment by Amber1990Zhang** [comment]
@whitewum Please note.

**Comment by nianiaJR** [comment]
This have been fixed.
