### ISSUE TITLE
can‘t import edges when I finish vertices

### ISSUE THREAD

**Issue by Amber1990Zhang** [vesoft-inc/nebula-web-docker#39]
![image](https://user-images.githubusercontent.com/42762957/78977912-84dc1180-7b4b-11ea-87fe-5f7606b2853c.png)
This issue happens before but not easy to reproduce. I'm 100% sure there are no errors in the previous step.

**Comment by Amber1990Zhang** [comment]
![image](https://user-images.githubusercontent.com/42762957/78979220-fcab3b80-7b4d-11ea-8694-ea5dc3bc03e2.png)
![image](https://user-images.githubusercontent.com/42762957/78979245-0896fd80-7b4e-11ea-80a0-f14d755ce92b.png)
![image](https://user-images.githubusercontent.com/42762957/78979257-1056a200-7b4e-11ea-80e2-3bd801ac34b3.png)

**Comment by nianiaJR** [comment]
If you have found it next time, please check if you have some config unfinished?

**Comment by nianiaJR** [comment]
not found now
