### ISSUE TITLE
v1.0.3 命令框的高度会变化

### ISSUE THREAD

**Issue by whitewum** [vesoft-inc/nebula-web-docker#43]
![image](https://user-images.githubusercontent.com/50101159/79101848-117d0e80-7d9c-11ea-9b72-5cc8bafb3757.png)

现在只有个很窄的窗口了，而且似乎不能调整

**Comment by whitewum** [comment]
![image](https://user-images.githubusercontent.com/50101159/79101918-396c7200-7d9c-11ea-89ff-71986b38b41a.png)

输入几个命令之后，又变宽了。

**Comment by NicolaCage** [comment]
https://github.com/vesoft-inc-private/nebula-web-console/commit/af62671b0066c5669953b04907ec63f48d4d43df
