### ISSUE TITLE
功能需求：“添加起点”这个功能，应该允许用户根据属性来查找起点

### ISSUE THREAD

**Issue by whitewum** [vesoft-inc/nebula-web-docker#47]
LOOKUP语法在Nebula里面已经支持了，对于用户来说，用属性找到起点，远比用vid来找起点要常用的多。

**Comment by NicolaCage** [comment]
lookup要基于索引，如果没有索引会报错。当前错误码都是一样没法区别是缺少索引还是语句错误，可能要等2.0统一错误码了

**Comment by whitewum** [comment]
那前端功能至少可以先开发啊，可以去查询有没有这个索引的

show index 这些。

**Comment by NicolaCage** [comment]
根据上次我们讨论，因为检测到没有index的话需要提供给用户一个这样的渠道去创建，不然现在做也不能光报错交互也很差。我们应该会在这次saas try版发布之后 开始讨论设计开发可视化建模和可视化创建index，可以放这期一起做。

**Comment by hetao92** [comment]
图探索索引查询已上线
