### ISSUE TITLE
功能需求：我希望edge type可以同时选择多种边类型

### ISSUE THREAD

**Issue by whitewum** [vesoft-inc/nebula-web-docker#49]
![image](https://user-images.githubusercontent.com/50101159/79102813-16db5880-7d9e-11ea-8480-fdb344d3b5d3.png)

当前下拉的意思，是只能选一种边类型，但是我在使用的时候，希望能把多种边都选上。

边方向我也希望有流入、流出、双向三个选择

**Comment by nianiaJR** [comment]
双向有个问题，目前我们的双向查询返回的数据没法判断方向，但实际数据存的时候是有方向性的，不不能准确表达vertices之间的关系，所以我去掉了。

**Comment by nianiaJR** [comment]
边的多选近期可以加上

**Comment by whitewum** [comment]
从使用者的角度说，我并不会关心存储方向是怎么实现的，我更关心我要双向遍历。
从实现的角度说，这个问题要下推到DB去推动解决。
在图探索上，没法双向遍历，功能就弱鸡了好多。特别是当要看3-5层的时候，正反来回添加非常非常麻烦

**Comment by nianiaJR** [comment]
我可以加上的是多边的选择，后面那个双向选择问题，得一起讨论下 @CPWstatic @jude-zhu

**Comment by nianiaJR** [comment]
一次多条边探索支持的PR：https://github.com/vesoft-inc-private/nebula-web-console/pull/101
