### ISSUE TITLE
功能需求：我希望能同时选中多个点，然后开始扩展

### ISSUE THREAD

**Issue by whitewum** [vesoft-inc/nebula-web-docker#50]
![image](https://user-images.githubusercontent.com/50101159/79103111-9537fa80-7d9e-11ea-8728-bd1478974ae9.png)

如图，我已经选出了 101,102,106,107 点，然后我要看它们的扩展。现在只能一个个点来选，我其实是希望同时扩展（一个个选“扩展”的方式太麻烦了，有过滤条件的）

**Comment by whitewum** [comment]
我注意到框选可以选中 框内的所有点，问题是我不能框选，想用shift ctrl来多选呢？

**Comment by nianiaJR** [comment]
https://github.com/vesoft-inc-private/nebula-web-console/pull/103/files 安排上了，pr中，cmd + 鼠标点击多选

**Comment by whitewum** [comment]
> https://github.com/vesoft-inc-private/nebula-web-console/pull/103/files 安排上了，pr中，cmd + 鼠标点击多选

可怜的windows键盘呢？

**Comment by nianiaJR** [comment]
> > https://github.com/vesoft-inc-private/nebula-web-console/pull/103/files 安排上了，pr中，cmd + 鼠标点击多选
> 
> 可怜的windows键盘呢？

windows是 win键哈，快捷键提示少我看看放在那里比较合适

**Comment by whitewum** [comment]
windows惯例是shift或者control。win按钮默认是windows的“开始”，可能会冲突。

**Comment by whitewum** [comment]
windows 用户使用后表示
win键这个交互 sucks

**Comment by nianiaJR** [comment]
这个我们想一下，control是chrome这些浏览器快捷键也有冲突，win键在浏览器打开的情况下还会冲突么？

**Comment by whitewum** [comment]
> 这个我们想一下，control是chrome这些浏览器快捷键也有冲突，win键在浏览器打开的情况下还会冲突么？

windows 下随便在哪里按win键，都是打开“开始”菜单。

**Comment by whitewum** [comment]
shift alt ctr 就这几个在win下可以。

**Comment by NicolaCage** [comment]
现在是按住shift多选， mac,win都是一样
