### ISSUE TITLE
bug: 字母不应该 上下颠倒显示（这样对人阅读毫无意义）

### ISSUE THREAD

**Issue by whitewum** [vesoft-inc/nebula-web-docker#52]
![image](https://user-images.githubusercontent.com/50101159/79103496-463e9500-7d9f-11ea-9737-c3f5c1477947.png)

边上的serve字段这样显示似乎毫无意义，没有人会这么看的

**Comment by nianiaJR** [comment]
这个已经改善发版了

**Comment by whitewum** [comment]
![image](https://user-images.githubusercontent.com/50101159/80360047-55e6cf00-88b1-11ea-9e96-c3bd5c50db5d.png)
我想并没有解决

**Comment by nianiaJR** [comment]
有更新么？看效果有的和我们已经处理的不太符合

**Comment by NicolaCage** [comment]
这个已经修复，应该是版本跟新的问题
