### ISSUE TITLE
疑问：缩放 这个按钮完全不知道是做什么的

### ISSUE THREAD

**Issue by whitewum** [vesoft-inc/nebula-web-docker#53]
我尝试把 节点和边 都放置到屏幕四周，我以为缩放这个按钮是重新排列的意思，但并不是。

![image](https://user-images.githubusercontent.com/50101159/79103602-7f770500-7d9f-11ea-9bb2-d99de765e94f.png)

**Comment by NicolaCage** [comment]
缩放按钮是用来控制整个画布的缩放开启或关闭

**Comment by whitewum** [comment]
可是我点了好久，没也看出来是zoom in还是zoom out...什么反应都没有

**Comment by NicolaCage** [comment]
![image](https://user-images.githubusercontent.com/37568394/83706765-ed76d480-a64a-11ea-85e1-1e3b614454fe.png)
现在改成了这种交互
