### ISSUE TITLE
优化： "清除" 按钮需要给提示

### ISSUE THREAD

**Issue by whitewum** [vesoft-inc/nebula-web-docker#54]
切换space的时候，有个提示

![image](https://user-images.githubusercontent.com/50101159/79103672-9fa6c400-7d9f-11ea-95b7-dfe750b74769.png)

1. 但是点击 "清除"按钮，没有任何提示，屏幕就被清空了。应该有个提示。

2. “清除”-> "清除显示" 文案这样更合适。强调并不是清除DB数据的意思。

**Comment by NicolaCage** [comment]
文案已经修成(是否清除当前视图) 代码已经合入 https://github.com/vesoft-inc-private/nebula-web-console/commit/5fc5e0c1bc5fc172ae5234167a8c9d7ffe5089d9
