### ISSUE TITLE
优化：History List 的关闭按钮

### ISSUE THREAD

**Issue by whitewum** [vesoft-inc/nebula-web-docker#58]
![image](https://user-images.githubusercontent.com/50101159/79104948-32486280-7da2-11ea-9c9d-54a37380b8be.png)

右上角的关闭X，不应该随着下拉后就不见了

**Comment by NicolaCage** [comment]
这个问题已经修复，https://github.com/vesoft-inc-private/nebula-web-console/commit/5fc5e0c1bc5fc172ae5234167a8c9d7ffe5089d9，已经合入发布了
