### ISSUE TITLE
需求：在屏幕底部加一个文本框，显示图探索时候的query

### ISSUE THREAD

**Issue by whitewum** [vesoft-inc/nebula-web-docker#65]
这样可以帮助用UI的用户开始熟悉 query。有些query就可以自己改造了，而不是依赖于UI

**Comment by whitewum** [comment]
当然，图探索如果能增加（CREATE） 节点就更好了

**Comment by nianiaJR** [comment]
由于一个图的显示会由多个query组成，目前仅显示探索关系这一步的query语句，打算先显示在下面这个位置：

**Comment by whitewum** [comment]
I'm ok
