### ISSUE TITLE
connection io timeout

### ISSUE THREAD

**Issue by SnakeHacker** [vesoft-inc/nebula-web-docker#67]

**Comment by SnakeHacker** [comment]
![image](https://user-images.githubusercontent.com/11294011/79590861-483f8580-810a-11ea-80f8-a0640c18e3db.png)

**Comment by SnakeHacker** [comment]
fixed, update `/etc/hosts` as follows
![image](https://user-images.githubusercontent.com/11294011/79629702-41525a80-817e-11ea-8e7f-a9864d2ae78e.png)

**Comment by mingfang** [comment]
I'm also seeing this problem.
What exactly is the cause and why do I have to edit `/etc/hosts`?

**Comment by nianiaJR** [comment]
> I'm also seeing this problem.
> What exactly is the cause and why do I have to edit `/etc/hosts`?

Do you use macOS?
![Uploading image.png…]()

**Comment by nianiaJR** [comment]
> fixed, update `/etc/hosts` as follows
> ![image](https://user-images.githubusercontent.com/11294011/79629702-41525a80-817e-11ea-8e7f-a9864d2ae78e.png)

I'm curious how you find the cause of modifying hosts, it seems to be a default config in computer system.
