### ISSUE TITLE
[优化]能否记住上次拓展的条件

### ISSUE THREAD

**Issue by whitewum** [vesoft-inc/nebula-web-docker#72]
第一拓展的时候，选择了一堆条件（边类型，参数，颜色）等等
拓展成功

然后我想第二次拓展，我费劲心力选择的条件呢？再重新选择一次？

**Comment by NicolaCage** [comment]
![image](https://user-images.githubusercontent.com/37568394/83706656-a092fe00-a64a-11ea-98ed-d88fe5bec5dd.png)
现在保存了上次拓展的条件，已经发布跟新了
