### ISSUE TITLE
当上传文件的列里面含有逗号是，文件会解析错误

### ISSUE THREAD

**Issue by jude-zhu** [vesoft-inc/nebula-web-docker#75]
数据如下
![image](https://user-images.githubusercontent.com/51590253/81642873-f95de500-9456-11ea-88ca-9af6381dce43.png)

文本打开：
![image](https://user-images.githubusercontent.com/51590253/81642891-0bd81e80-9457-11ea-924a-641757c0d416.png)

当上传到 studio
![image](https://user-images.githubusercontent.com/51590253/81642926-1beffe00-9457-11ea-9e59-f56bcb3b6416.png)

**Comment by NicolaCage** [comment]
这个修复了，pr合进去了
