### ISSUE TITLE
[优化] 显示属性的时候，选择是否需要同时显示schema

### ISSUE THREAD

**Issue by whitewum** [vesoft-inc/nebula-web-docker#82]
![image](https://user-images.githubusercontent.com/50101159/82430524-fea6d980-9abf-11ea-9a3c-f6c589d9348b.png)
以这张图为例，player.name 这个几个字符，每个点上都显示一下，其实有点重复。如果用户可以选择显示"player.name:Lamarcu"或者"Lamarcus"，体验会好一丢丢

**Comment by NicolaCage** [comment]
让用户选择不显示属性名 而显示属性值是吗？那如果有多条属性值，那用户会不会分不清

**Comment by NicolaCage** [comment]
这个修复了  上周发布了，边属性自定义勾选显示
