### ISSUE TITLE
[bug]没看懂这个空tab是干啥的

### ISSUE THREAD

**Issue by whitewum** [vesoft-inc/nebula-web-docker#83]
![image](https://user-images.githubusercontent.com/50101159/82431286-0c109380-9ac1-11ea-91ce-bca3d6725568.png)

**Comment by Amber1990Zhang** [comment]
我记得我没有遇到过这种问题啊

**Comment by NicolaCage** [comment]
![image](https://user-images.githubusercontent.com/37568394/83706582-717c8c80-a64a-11ea-9f54-2fe3e1b5e0ec.png)
这个修复了
