### ISSUE TITLE
[bug] 添加起点的时候，如果没有这个点，为什么要在画布上显示，这是完全的误导

### ISSUE THREAD

**Issue by whitewum** [vesoft-inc/nebula-web-docker#84]
不存在的点，就完全不应该显示出来。

比如500这个点根本就没有，为什么要画出来这，这个完全不能接受啊。

而且点击了还左上角显示vertexid 500，扯淡嘛

![image](https://user-images.githubusercontent.com/50101159/82431565-601b7800-9ac1-11ea-9525-7ac3432c1b09.png)

**Comment by Amber1990Zhang** [comment]
而且我觉得这里叫添加起点有点歧义，添加起点有点类似于 INSERT VERTEX，而实际上此处是选择顶点以进行可视化探索

**Comment by NicolaCage** [comment]
我们添加视图起点的时候做了检查，如果数据中不存在改vid，提示用户当前节点不存在 并且不显示
