### ISSUE TITLE
[bug]错误提示完全non sense

### ISSUE THREAD

**Issue by whitewum** [vesoft-inc/nebula-web-docker#85]
1. 错误提示应该是红色，不应该是蓝色
2. DB返回的错误要显示在整个文本的最前方，而不是打印一大段用户输入的query。query我上面就能看到，再给我显示一遍没有意义啊。

**Comment by nianiaJR** [comment]
fixed https://github.com/vesoft-inc-private/nebula-web-console/commit/ec2e1a5b7cc636a5a8b4ebef69442302cbd77754#diff-4348e40e3e6b453791d758fe4a73b09eR86
