### ISSUE TITLE
所有csv文件都少读了一列数据

### ISSUE THREAD

**Issue by Amber1990Zhang** [vesoft-inc/nebula-web-docker#89]
![image](https://user-images.githubusercontent.com/42762957/82542721-0bd9cc00-9b85-11ea-8438-441ee2b9d7ad.png)
预览时发现所有csv文件都少读了一列数据，配置点边时发现也少了一列，属性没法选。
![image](https://user-images.githubusercontent.com/42762957/82542868-46dbff80-9b85-11ea-86d8-ee5896cfc820.png)
到age属性就没了。

**Comment by nianiaJR** [comment]
already fixed

**Comment by nianiaJR** [comment]
https://github.com/vesoft-inc-private/nebula-web-console/commit/0211069937ed70c5f159644babe0fe72ac4efeff
