### ISSUE TITLE
时而报错时而不报错

### ISSUE THREAD

**Issue by Amber1990Zhang** [vesoft-inc/nebula-web-docker#90]
不同的属性选择同一个列，继续导入操作，有时候会报错，报错信息如下：
![image](https://user-images.githubusercontent.com/42762957/82543034-8efb2200-9b85-11ea-96c4-f097cfcae965.png)
有时候又会显示成功，如下：
![image](https://user-images.githubusercontent.com/42762957/82543147-ae924a80-9b85-11ea-9444-cc36eed1d2a8.png)

**Comment by NicolaCage** [comment]
我们确实没法复现，而且现在更改了校验逻辑，我觉得这个问题应该不会出现了
