### ISSUE TITLE
nGQL拼接问题

### ISSUE THREAD

**Issue by Amber1990Zhang** [vesoft-inc/nebula-web-docker#91]
![image](https://user-images.githubusercontent.com/42762957/82543507-3a0bdb80-9b86-11ea-890f-d8309f49096a.png)
见上图，执行不成功，报错

**Comment by nianiaJR** [comment]
fixed https://github.com/vesoft-inc-private/nebula-web-console/commit/0211069937ed70c5f159644babe0fe72ac4efeff
