### ISSUE TITLE
图探索条件筛选失败

### ISSUE THREAD

**Issue by Amber1990Zhang** [vesoft-inc/nebula-web-docker#94]
![image](https://user-images.githubusercontent.com/42762957/82544290-7f7cd880-9b87-11ea-8fc6-0ecf4a183e98.png)
![image](https://user-images.githubusercontent.com/42762957/82544072-21e88c00-9b87-11ea-95b4-88c75f3c1710.png)
执行失败，但是我觉得我的语句是正确的。

**Comment by NicolaCage** [comment]
这个是已经修复了，你获取最新的镜像再试试
